### PR TITLE
NMS-9861: get postgres service

### PR DESCRIPTION
**Pull request by cgorantla**

### CODE REVIEW

**Comment by mvrueden** [comment]
This looks good, but can we also provide a `getService(ContainerAlias, int)` method, which could be used as well, even if the convenient methods aren't yet provided.

**Comment by cgorantla** [comment]
Selenium has only two containers OpenNMS and Postgres. So this may be sufficient.

**Comment by mvrueden** [comment]
If we were talking about sufficient, we don't need the methods at all, as the m_testenvironment has everything we need.

**Comment by cgorantla** [comment]
@mvrueden  m_testEnvironment has private access, calling getTestEnvironment() also didn't help as it is ClassRule and resulting container is not valid

**Comment by mvrueden** [comment]
For possible options for ContainerAlias, please refer to (https://github.com/OpenNMS/opennms-system-test-api/blob/b9ebf55a72b26eda3744399952c303e7851a7815/src/main/java/org/opennms/test/system/api/NewTestEnvironment.java#L114)

If anyone needs to access anything other than Postgres or OpenNMS we are back were we started:
The provided solution is not very future proof. 

So I am still for adding some mechanism to get the other addresses if required, as it is easy to do.

**Comment by mvrueden** [comment]
Now I understand.
Nevermind my comments then.

**Pull request merged**
